[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  autoLaunch = true
  disableEdgeFunctions = true  # 添加这行临时禁用 Edge Functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200